added kycProof event, number_of_documents field to kyc_start event ty…
covery/php-client pull request #30
Opened 2021-01-26 14:29 UTC by andreynts

…pe, updated test and readme file

2021-01-27 16:32 UTC, avostrovskyi1989 requested changes

2021-01-27 16:32 UTC, avostrovskyi1989 commented on src/Envelopes/Builder.php
> +            //throw new \InvalidArgumentException('Incorrect value. Number Of Documents must contain 0, 1 or 2');
Зачем?

2021-01-27 16:32 UTC, avostrovskyi1989 commented on src/Envelopes/Builder.php
> +    public function addKycProofData($kycStartId = null)
Обязательное поле kycStartId

2021-01-27 16:32 UTC, avostrovskyi1989 commented on src/Envelopes/Builder.php
> +    public static function kycProofEvent($kycStartId = null)
kycStartId - обязательное поле

2021-01-27 16:32 UTC, avostrovskyi1989 commented on README.md
Changelog не указан.

2021-01-27 16:32 UTC, avostrovskyi1989 commented on src/Envelopes/Builder.php
> +     * Provides kuc proof value to envelope
kuc - typo

2021-01-27 16:32 UTC, avostrovskyi1989 commented on src/PublicAPIClient.php
> +    public function sendKycProof(EnvelopeInterface $envelope)
Непонятно что этот метод возвращает. Предлагаю созадть отдельный класс под ответ + комент (см. другие методы класса).

2021-01-27 16:32 UTC, avostrovskyi1989 commented on src/Facade.php
> +     * @return mixed|null
отдельный класс под ответ. Нужно двигаться в сторону строгой типизации.

2021-01-27 16:32 UTC, avostrovskyi1989 commented on src/Envelopes/ValidatorV1.php
> +                $this->analyzeFieldTypes($envelope)
почему нет this->analyzeTypeAndMandatoryFields?

2021-01-28 07:50 UTC, andreynts commented on src/Envelopes/Builder.php
> +            //throw new \InvalidArgumentException('Incorrect value. Number Of Documents must contain 0, 1 or 2');
согласно таске данное поле необязательное и если значение не переданное или содержит некорректное значени (не 1, 2 или 0) то используется значение 1 по умолчанию

2021-01-28 07:53 UTC, andreynts commented on src/Envelopes/Builder.php
> +    public function addKycProofData($kycStartId = null)
обновил

2021-01-28 07:53 UTC, andreynts commented on src/Envelopes/Builder.php
> +    public static function kycProofEvent($kycStartId = null)
обновил

2021-01-28 09:21 UTC, andreynts commented on src/Envelopes/ValidatorV1.php
> +                $this->analyzeFieldTypes($envelope)
добавил проверку

2021-01-28 09:22 UTC, andreynts commented on src/Facade.php
> +     * @return mixed|null
вынес в отдельный класс KycProofResult

2021-01-28 09:23 UTC, andreynts commented on src/PublicAPIClient.php
> +    public function sendKycProof(EnvelopeInterface $envelope)
вынес в отдельный класс ответ и добавил в коммент тип возврата

2021-01-28 10:23 UTC, andreynts commented on README.md
обновил

2021-01-28 12:00 UTC, avostrovskyi1989 commented on README.md
> +  * Added optional `number_of_docyments` field for kyc_start event.
typo

2021-01-28 12:00 UTC, avostrovskyi1989 commented on src/Envelopes/Builder.php
> +            throw new \InvalidArgumentException('Incorrect value. Number Of Documents must contain 0, 1 or 2');
`contains` not `contain`  in the exception message.

2021-01-28 12:00 UTC, avostrovskyi1989 commented on src/PublicAPIClient.php
> +            return new KycProofResult(
Ну такое создавать обьект внутри блока try - catch

2021-01-28 12:41 UTC, avostrovskyi1989 approved these changes

2021-02-11 10:38 UTC, merged

2021-02-11 10:39 UTC, avostrovskyi1989 commented
Merge added kycProof event, number_of_documents field to kyc_start event type